publish:
  windows_direct: windows_direct
  windows_proxy: windows_proxy
  android_proxy: android_proxy

lists_local:
  windows_direct:
    - windows_torrent-clients
    - windows_games

  windows_proxy:
    - windows_proxy

  android_proxy:
    - android_proxy
