publish:
  pc-direct: pc-direct
  pc-proxy: pc-proxy
  android-proxy: android-proxy

lists_local:
  pc-direct:
    - pc-torrent-clients
    - pc-games

  pc-proxy:
    - pc-proxy

  android-proxy:
    - android-proxy
