publish:
  windows-direct: windows-direct
  windows-proxy: windows-proxy
  android-proxy: android-proxy

lists_local:
  windows-direct:
    - windows-torrent-clients
    - windows-games

  windows-proxy:
    - windows-proxy

  android-proxy:
    - android-proxy
