country_code: ru

asn_path: asn
ips_path: ips

publish:
  whitelist: whitelist
  direct: direct
  blocked: proxy

asn_lists:
  whitelist:
    - yandex
    - vk

  direct:
    - whitelist
    - gosuslugi

  blocked: []

ip_lists:
  whitelist:
    - dns-whitelist

  direct:
    - whitelist

  blocked:
    - blocked
    - dns-proxy

sources:
  blocked:
    - https://antifilter.download/list/ip.lst
    - https://www.cloudflare.com/ips-v4
    - https://raw.githubusercontent.com/GhostRooter0953/discord-voice-ips/master/voice_domains/discord-voice-ip-list
