asn_lists:
  ru-whitelist:
    - yandex
    - vk

  ru-direct:
    - ru-whitelist
    - gosuslugi

  ru-blocked: []

ip_lists:
  ru-whitelist:
    - dns-whitelist

  ru-direct:
    - ru-whitelist

  ru-blocked:
    - blocked
    - dns-proxy

publish:
  ru-whitelist: geoip_whitelist
  ru-direct: geoip_direct
  ru-blocked: geoip_proxy

sources:
  blocked:
    - https://antifilter.download/list/ip.lst
    - https://www.cloudflare.com/ips-v4
    - https://raw.githubusercontent.com/GhostRooter0953/discord-voice-ips/master/voice_domains/discord-voice-ip-list

asn_path: asn
ips_path: ips
