name: Normalize Files Action
description: Удаляет мусор из строки

inputs:
  input_path:
    description: Путь к папке или одиночному файлу
    required: true
  output_path:
    description: Путь к директории для сохранения результата
    required: true
  prefix:
    description: Префикс конечного файла
    required: false
    default: ""
  ext:
    description: Расширение конечного файла
    required: false
    default: ""

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        process_file() {
          local file="$1"
          local in_path="${{ inputs.input_path }}"
          local out_path="${{ inputs.output_path }}"
          local raw_prefix="${{ inputs.prefix }}"
          local prefix="${raw_prefix:+"${raw_prefix}_"}"
          local raw_ext="${{ inputs.ext }}"

          filename=$(basename "$file")
          if [ -n "$raw_ext" ]; then
            name="${filename%.*}"
            filename="${name}.${raw_ext}"
          fi

          [ -e "$file" ] || return 0  
          sed "
            s/#.*//;                 # Удалить всё после символа #
            s/^[[:space:]{}\"']*//;  # Удалить пробелы и кавычки в начале
            s/[[:space:]{}\"']*$//;  # Удалить пробелы и кавычки в конце
            /^$/d                    # Удалить пустые строки
          " "$file" > "${out_path}/${prefix}${filename}"

          echo "${out_path}/${prefix}${filename}"
          
          rm "$file"
        }

        ls -R "${in_path}"

        if [ -d "${in_path}" ]; then
          # Если это директория — перебираем файлы
          for f in "${in_path}"/*; do
            [ -f "$f" ] && process_file "$f"
          done
        elif [ -f "${in_path}" ]; then
          # Если это одиночный файл — обрабатываем его
          process_file "${in_path}"
        else
          echo "Warning: Path ${in_path} not found."
        fi
