name: Build GeoIP
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CURL: "curl -fsSL --retry 3 --retry-delay 2 --retry-connrefused"
      OUTPUT_PATH: output

    steps:
      # Install dependencies
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Loyalsoldier/geoip
        uses: actions/checkout@v4
        with:
          repository: Loyalsoldier/geoip
          path: geoip

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: geoip/go.mod
          cache-dependency-path: geoip/go.sum

      # Build
      - name: Build GeoIP
        run: |
          # Загрузка данных
          mkdir -p ./geolite2
          ${{ env.CURL }} --output-dir ./geolite2 -O https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-ASN-Blocks-IPv4.csv

          # Сборка
          go build -C geoip .
          geoip/geoip convert -c geoip_v2ray_config.json

          # Перемещение результатов
          process_files() {
            local dir=$1
            local ext=$2

            # ru-blocked -> geoip_proxy
            if [ -f "output/$dir/ru-blocked.$ext" ]; then
              mv "output/$dir/ru-blocked.$ext" "output/geoip_proxy.$ext"
            fi

            # ru-whitelist -> geoip_whitelist
            if [ -f "output/$dir/ru-whitelist.$ext" ]; then
              mv "output/$dir/ru-whitelist.$ext" "output/geoip_direct.$ext"
            fi

            # * -> geoip_*
            for f in output/$dir/*.$ext; do
              if [ -f "$f" ]; then
                mv "$f" "output/geoip_$(basename "$f")"
              fi
            done

            # Очистка данных
            rm -rf output/$dir/
          }

          process_files "srs" "srs"
          process_files "mrs" "mrs"
          process_files "text" "lst"

          # Вывод списка итоговых данных
          ls -lR ./output

      # Uploading results
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geoip-output
          path: output
